function Games(){};function Flash(){};Flash.Notes={};Flash.Notes.Keyboard={};Games.Common={};Games.Common.displayScore=function(){statusView.displayPoints("#status_points",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#status_percent",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#status_score",statusModel.getScore());statusView.displayLevel("#status_level",statusModel.getLevel());statusView.displayHiScore("#hi_score",statusModel.getHiScore())};
Games.Common.displaySummary=function(){$("#game_frame").hide();$("#staff_paper").hide();statusView.displayPoints("#point_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#percent_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#score_summary",statusModel.getScore());$("#time_summary_row").hide();$("#score_summary_row").show();$("#level_summary_row").show();$("#lives_summary_row").show();$("#next_level_row").show();$("#level_summary").html(""+
statusModel.getLevel());$("#lives_summary").html(""+statusModel.getLives());$("#summary_frame").show()};Games.Common.removeLivesDisplay=function(){statusView.removeLivesDisplay()};
Games.Common.displaySessionAlert=function(a,b,c){$("#menu_frame").hide();$("#instructions_frame").hide();$("#summary_frame").hide();$("#game_frame").hide();$("#staff_paper").hide();$("#menu_buttons").hide();$("#session_frame").show();$("#game_status_box").show();a&&!b?($("#session_start_header").html("Level "+statusModel.getLevel()),$("#session_end").hide(),$("#game_end").hide(),$("#session_start").show(),$("#session_start_button").focus()):b?($("#session_start").hide(),$("#session_end").hide(),$("#game_end").show(),
$("#scores_button").focus()):($("#session_start").hide(),$("#game_end").hide(),lives=statusModel.getLives(),lives_str=1<lives?" lives":" life",$("#lives").html(""+statusModel.getLives()+lives_str+" left"),c?($("#session_end_header").html("Good Job!"),$("#bonus").html("BONUS PTS<br/>"+statusModel.getBonus())):($("#session_end_header").html("Same Level"),$("#bonus").html("BONUS PTS<br/>0")),$("#session_end").show(),$("#session_end_button").focus())};
Games.Common.processFinalScore=function(){var a,b;a=statusModel.getScore();var c,d;statusModel.setDate();b=statusModel.getDateTime();c=statusModel.getDateString();d=statusModel.getTimeString();b="score="+a+"&time="+b+"&date_string="+c+"&time_string="+d;Modernizr.localstorage?(c=statusModel.getHiScore(),statusModel.setHiScore(c>a?c:a)):statusModel.setHiScore(a);$("#score_text").html("Please wait . . . retrieving scores");ajaxUtilities.createXHR();a=ajaxUtilities.getXHR();ajaxUtilities.open("POST",
"php/get_scores.php");a.onreadystatechange=ajaxUtilities.onChange;ajaxUtilities.send("POST",b)};
Games.Common.displayFinalScore=function(a){var b,c,d,e="",f="",g="",h="your score: "+statusModel.getScore(),k=statusModel.top_scores.length;if(a)for(a=0;a<k;a++)b=parseInt(statusModel.top_scores[a]),c=statusModel.top_date_strings[a],d=parseInt(statusModel.top_times[a]),b===statusModel.getScore()&&d===statusModel.getDateTime()?(e+='<span class="your_scores">'+(a+1)+".</span><br />",f+='<span class="your_scores">'+b+"*</span><br />",g+='<span class="your_scores">'+c+"</span><br />",h="* your score"):
(e+=a+1+".<br />",f+=b+"<br />",g+=c+"<br />");else for(a=0;10>a;a++)e+=a+1+".<br />",f+="unavailable<br />",g+="unavailable<br />";$("#score_display_frame").show();$("#main_menu_button").focus();$("#top_rank").html(e);$("#top_scores").html(f);$("#top_dates").html(g);$("#top_score_footer").html(h)};Games.Common.AjaxUtilities=function(){var a,b,c=!1;this.createXHR=function(){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};this.getXHR=function(){return a};this.open=function(b,e){try{a.open(b,e,!0)}catch(f){c=!1}};this.send=function(b,e){try{a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(e)}catch(f){c=!1}};this.onChange=function(){var d,e,f;if(4===a.readyState){if(200===a.status||"OK"===a.statusText){c=!0;try{for(b=a.responseXML,
e=b.getElementsByTagName("score"),f=b.getElementsByTagName("time"),ds=b.getElementsByTagName("date_string"),ts=b.getElementsByTagName("time_string"),d=0;d<e.length;d++)statusModel.top_scores[d]=e[d].childNodes[0].nodeValue,statusModel.top_times[d]=f[d].childNodes[0].nodeValue,statusModel.top_date_strings[d]=ds[d].childNodes[0].nodeValue,statusModel.top_time_strings[d]=ts[d].childNodes[0].nodeValue}catch(g){c=!1}}else c=!1;Games.Common.displayFinalScore(c);$("#main_menu_button").show()}}};Flash.Notes.Keyboard.noteRangeProperties=function(a){return Flash.Notes.Keyboard.noteRangeProperties.table[a]};
Flash.Notes.Keyboard.noteRangeProperties.table={0:{base_index:[1,6,4,2],base_octave:[4,3,3,4],upper_index:[4,6,1,3],upper_octave:[5,5,6,6]},1:{base_index:[3,1,6,4],base_octave:[2,2,1,1],upper_index:[6,1,3,5],upper_octave:[3,4,4,4]},2:{base_index:[2,0,5,3],base_octave:[3,3,2,2],upper_index:[5,0,2,4],upper_octave:[4,5,5,5]},3:{base_index:[0,5,3,1],base_octave:[3,2,2,2],upper_index:[3,5,0,2],upper_octave:[4,4,5,5]}};Flash.Notes.Keyboard.keyIdToElementId=function(a){return Flash.Notes.Keyboard.keyIdToElementId.table[a]};
Flash.Notes.Keyboard.keyIdToElementId.table={a:"c",w:"cs",s:"d",e:"ds",d:"e",f:"f",t:"fs",g:"g",y:"gs",h:"a",u:"as",j:"b",k:"c"};Flash.Notes.Keyboard.keySignatureAccidentals=function(a,b){void 0===a&&(a="C");return Flash.Notes.Keyboard.keySignatureAccidentals.table[a][b]};
Flash.Notes.Keyboard.keySignatureAccidentals.table={C:"      ".split(" "),"C#":"#######".split(""),Cb:"bbbbbbb".split(""),D:"#   #   ".split(" "),Db:" b b  b b b".split(" "),E:"# #  # #  ".split(" "),Eb:"  b   b b".split(" "),F:"      b".split(" "),"F#":"# # # # # # ".split(" "),G:"   #   ".split(" "),Gb:"b b b  b b b".split(" "),A:"#   # #  ".split(" "),Ab:" b b   b b".split(" "),B:"# #  # # # ".split(" "),Bb:"  b    b".split(" ")};function Merge(a,b){for(var c in b)a[c]=b[c];return a}function randomPos(a){return Math.floor(Math.random()*a)}function saveData(a,b){Modernizr.localstorage&&localStorage.setItem(a,b)}function getData(a){if(Modernizr.localstorage)return localStorage.getItem(a)};$(document).ready(function(){var a="awsedftgyhujk".split(""),b="#c #cs #d #ds #e #f #fs #g #gs #a #as #b #c2".split(" ");Modernizr.canvas?(cfg=new Flash.Notes.Keyboard.Config,statusModel=new Flash.Notes.Keyboard.StatusModel,statusView=new Flash.Notes.Keyboard.StatusView,notationModel=new Games.Notation.NotationModel,notationController=new Games.Notation.NotationController,gameController=new Flash.Notes.Keyboard.GameController,$(".accid_sel_Btn").addClass("off"),$("#stop").hide(),$("#menu_frame").show(),
$("#practice_button").focus(),$("#practice_button").click(function(){gameController.displayPractice()}),$("#practice_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#instructions_button").focus();a===cfg.DOWN_KEY&&$("#play_button").focus()}),$("#play_button").click(function(){gameController.displayGame()}),$("#play_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#practice_button").focus();a===cfg.DOWN_KEY&&$("#instructions_button").focus()}),$("#instructions_button").click(function(){$("#menu_frame").hide();
$("#instructions_frame").show();$("#back_button").focus()}),$("#instructions_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#play_button").focus();a===cfg.DOWN_KEY&&$("#show_top_scores_button").focus()}),$("#show_top_scores_button").keydown(function(a){a=parseInt(a.keyCode);a===cfg.UP_KEY&&$("#instructions_button").focus();a===cfg.DOWN_KEY&&$("#practice_button").focus()}),$("#show_top_scores_button").click(function(){$("#menu_frame").hide();$("#score_display_frame").show();
gameController.processFinalScore()}),$("#back_button").click(function(){$("#instructions_frame").hide();$("#menu_frame").show();$("#practice_button").focus()}),$("#start_button").click(function(){gameController.getStart()||($(this).hide(),$("#stop_button").show());gameController.startGame("#status_timer")}),$("#stop_button").click(function(){gameController.getStart()&&($(this).hide(),$("#start_button").show());gameController.stopGame();$("#sum_continue_button").focus()}),$(".black_key_Btn").keydown(function(c){var d;
d=parseInt(c.keyCode);"13"===d&&c.preventDefault();65<=d&&89>=d&&(c=statusModel.getKeyIndex(d),-1!=c&&(d=a[c],k_btn=b[c],$(k_btn).css("background-color","#127"),gameController.continueGame(c,d)))}),$(".black_key_Btn").keyup(function(a){var d=parseInt(a.keyCode);"13"===d&&a.preventDefault();65<=d&&89>=d&&(a=statusModel.getKeyIndex(d),-1!=a&&(k_btn=b[a],$(k_btn).css("background-color","#000")))}),$(".white_key_Btn").keydown(function(c){var d;d=c.keyCode;"13"===d&&c.preventDefault();65<=d&&89>=d&&(c=
statusModel.getKeyIndex(d),-1!=c&&(d=a[c],k_btn=b[c],$(k_btn).css("background-color","#127"),gameController.continueGame(c,d)))}),$(".white_key_Btn").keyup(function(a){var d=a.keyCode;"13"===d&&a.preventDefault();65<=d&&89>=d&&(a=statusModel.getKeyIndex(d),-1!=a&&(k_btn=b[a],$(k_btn).css("background-color","#fff")))}),$(".black_key_Btn").click(function(){var b=$(this).attr("value");keyId=a[b];gameController.continueGame(b,keyId)}),$(".white_key_Btn").click(function(){var b=$(this).attr("value");gameController.continueGame(b,
a[b])}),$(".overlay").click(function(){gameController.toggleKeyOverlay()}),$(".clefBtn").click(function(){var a=parseInt($(this).attr("value"));gameController.toggleClef(a);$("#c").focus()}),$(".accid_sel_Btn").click(function(){var a=$(this).attr("value");gameController.toggleAccidental(a);$("#c").focus()}),$(".keysig_sel_Btn").click(function(){var a=$(this),a=parseInt(a.attr("value"));gameController.updateKeySignature(a);$("#c").focus()}),$("#session_start_button").click(function(){$("#session_frame").hide();
statusModel.setTimeout(!1);$("#game_frame").show();gameController.startGame("#status_timer")}),$("#session_end_button").click(function(){$("#session_frame").hide();gameController.displaySummary();$("#sum_continue_button").focus()}),$("#scores_button").click(function(){$("#session_frame").hide();gameController.processFinalScore()}),$("#sum_continue_button").click(function(){$("#summary_frame").hide();$("#session_frame").hide();statusModel.getTimeout()||statusModel.getMode()!==statusModel.GAME_MODE||
gameController.startGame("#timer");statusModel.getTimeout()?gameController.updateLevel():$("#game_frame").show();$("#c").focus()}),$("#sum_continue_button").keydown(function(a){a=a.keyCode;if(a===cfg.UP_KEY||a===cfg.DOWN_KEY)$(this).blur(),$("#quit_button").focus()}),$("#quit_button").click(function(){$("#summary_frame").hide();statusModel.getMode()===cfg.GAME_MODE?(gameController.processFinalScore(),gameController.removeLivesDisplay(),$("#score_display_frame").show()):($("#menu_frame").show(),$("#practice_button").focus())}),
$("#quit_button").keydown(function(a){a=a.keyCode;a!==cfg.UP_KEY&&a!==cfg.DOWN_KEY||$("#sum_continue_button").focus()}),$("#main_menu_button").click(function(){$("#score_display_frame").hide();$("#main_menu_button").hide();gameController.init();$("#menu_frame").show();$("#practice_button").focus()}),$("button").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:.9})}),$(".overlay").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:.7})}),$(".black_key_Btn").hover(function(){$(this).css({"background-color":"#127"});
$(this).css({opacity:1})},function(){$(this).css({"background-color":"#000"});$(this).css({opacity:1})}),$(".white_key_Btn").hover(function(){$(this).css({"background-color":"#66a"});$(this).css({opacity:1})},function(){$(this).css({"background-color":"#fff"});$(this).css({opacity:1})}),$(".black_key_Btn").mousedown(function(){$(this).css({"background-color":"#2f2"});$(this).css({opacity:1})}),$(".white_key_Btn").mousedown(function(){$(this).css({"background-color":"#2f2"});$(this).css({opacity:1})}),
$(".black_key_Btn").mouseup(function(){$(this).css({"background-color":"#000"});$(this).css({opacity:1})}),$(".white_key_Btn").mouseup(function(){$(this).css({"background-color":"#fff"});$(this).css({opacity:1})}),$(".keysig_sel_Btn").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:.95})})):$("#nocanvas_frame").show()});Games.Notation={};Flash.Notes.Keyboard.Config=function(){this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;this.TREBLE_OFFSET=10;this.BASS_OFFSET=12;this.ALTO_OFFSET=11;this.TENOR_OFFSET=9;this.PRACTICE_MODE=0;this.GAME_MODE=1;this.MAX_LEVEL=30;this.TIER_1=4;this.TIER_2=14;this.TIER_3=18;this.TIER_4=28;this.MIN_ATTEMPTS=5;this.MIN_PERCENT=80;this.TIMEOUT=12;this.BONUS_INC=this.BONUS=50;this.BONUS_LEVEL=12;this.MAX_LIVES=5;this.RANDOM_TB=4;this.RANDOM_AT=5;this.RANDOM_ALL=6;this.TOGGLE_OFF=0;this.TOGGLE_ON=1;this.TOGGLE_NONE=
-1;this.MIN_RANGE=0;this.MAX_RANGE=3;this.P_HIGH_PCT=70;this.P_LOW_PCT=60;this.PRACTICE_ATT=5;this.ENTER_KEY=13;this.ESC_KEY=27;this.UP_KEY=38;this.DOWN_KEY=40;this.KEY_C=65;this.KEY_CS=87;this.KEY_D=83;this.KEY_DS=69;this.KEY_E=68;this.KEY_F=70;this.KEY_FS=84;this.KEY_G=71;this.KEY_GS=89;this.KEY_A=72;this.KEY_AS=85;this.KEY_B=74;this.KEY_C2=75;this.SMALL="small";this.SMALL_W="small_w";this.NORMAL="normal";this.NORMAL_W="normal_w";this.MEDIUM="medium";this.MEDIUM_W="medium_w";this.LARGE="large";
this.LARGE_W="large_w";this.HUGE="huge";this.HUGE_W="huge_w";this.BG_STAVE_LEFT=20;this.BG_STAVE_TOP=10;this.BG_STAVE_WIDTH=100;this.BG_LAYER_WIDTH=320;this.BG_LAYER_HEIGHT=200;this.FG_STAVE_TOP=10;this.NOTE_LAYER_LEFT=this.KS_LAYER_LEFT=this.CLEF_LAYER_LEFT=0;this.CLEF_LAYER_WIDTH=70;this.KS_LAYER_WIDTH=100;this.NOTE_LAYER_WIDTH=146;this.CLEF_X=0;this.CLEF_WIDTH=70;this.NOTE_START_X=160;this.CLEF_TYPES=["treble","bass","alto","tenor"];this.MIN_RANGE_INDEX=0;this.MAX_RANGE_INDEX=3;this.ACC_LEVELS=
[5,6,19,20];this.KS_TIER_1=[7,14];this.KS_TIER_2=[21,30];this.KS_EASY_LEVELS=[7,8,11,12,21,22,25,26,29];this.KS_HARD_LEVELS=[9,10,13,14,23,24,27,28,30];this.EASY_KEYS=0;this.HARD_KEYS=1;this.ACC_SINGLE=0;this.ACC_DOUBLE=1;this.ACC_ALL=2;this.ACC_SINGLE_NOT_C=3;this.ACC_ALL_NOT_C=4;this.ACC_NONE=-1;this.ACC_TYPE_C=0;this.ACC_TYPE_FLAT=-1;this.ACC_TYPE_SHARP=1;this.ACCIDENTAL_ON={single_acc:!1,double_acc:!1};this.NATURAL="n";this.SHARP="#";this.DOUBLE_SHARP="##";this.FLAT="b";this.DOUBLE_FLAT="bb";
this.NONE="";this.C=7;this.CS=14;this.CF=0;this.D=9;this.DF=2;this.E=11;this.EF=4;this.F=6;this.FS=13;this.G=8;this.GF=1;this.A=10;this.AF=3;this.B=12;this.BF=5;this.KEY_SIGS="Cb Gb Db Ab Eb Bb F C G D A E B F# C#".split(" ");this.KS_C_INDEX=7;this.KS_EASY=[this.C,this.G,this.F,this.D,this.BF,this.A,this.EF];this.KS_HARD=[this.E,this.AF,this.B,this.DF,this.FS,this.GF,this.CS,this.CF];this.KS_SEL_WIDTH=55;this.KS_SEL_HEIGHT=45};InputModel=function(){this.answer=-1};InputModel.prototype.setNoteAnswer=function(a){a.charCodeAt(0);this.answer=$code-65;return this};InputModel.prototype.getNoteAnswer=function(){return this.answer};Games.Notation.NotationController=function(){this.backend=Vex.Flow.Renderer.Backends.CANVAS;Modernizr.canvas||(this.backend=Vex.Flow.Renderer.Backends.RAPHAEL);this.note_spacer=120};Games.Notation.NotationController.prototype.drawStaff=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();b=new Vex.Flow.Stave(b,c,d);a.setTransform(1,0,0,1,0,0);a.scale(e,e);b.setContext(a).draw(a,!1,!1);return b};
Games.Notation.NotationController.prototype.drawClef=function(a,b,c){a=document.getElementById(a);var d=(new Vex.Flow.Renderer(a,this.backend)).getContext();b.addClef(c);1<b.glyphs.length&&(b.glyphs[0]=b.glyphs[b.glyphs.length-1],b.glyphs.pop(b.glyphs.length-1),b.glyphs.pop(b.glyphs.length-1),d.clearRect(0,0,a.width,a.height));b.setContext(d).draw(d,!1,!1)};
Games.Notation.NotationController.prototype.drawNote=function(a,b,c,d,e,f,g){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();c=new Vex.Flow.StaveNote({keys:[c],duration:d,clef:b.clef});g&&c.addAccidental(0,new Vex.Flow.Accidental(g));b.setNoteStartX(f);this.note_spacer=f;Vex.Flow.Formatter.FormatAndDraw(a,b,[c],e);return c};
Games.Notation.NotationController.prototype.drawNotes=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();var f,g,h,k=[],l=[],m=[];for(f=0;f<c.length;f++){for(g=0;g<c[f].note_names.length;g++)k[g]=c[f].note_names[g],l[g]=c[f].accidentals[g];h=new Vex.Flow.StaveNote({keys:k,duration:c[f].note_dur,clef:b.clef});for(g=0;g<c[f].note_names.length;g++)l[g]&&h.addAccidental(g,new Vex.Flow.Accidental(l[g]));m[f]=h}b.setNoteStartX(e);Vex.Flow.Formatter.FormatAndDraw(a,
b,m,d);return h};Games.Notation.NotationController.prototype.addAccidental=function(a,b,c,d,e){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();c.addAccidental(d,new Vex.Flow.Accidental(e));b.setContext(a).draw(a,!1,!1)};
Games.Notation.NotationController.prototype.hideNote=function(a,b){var c=document.getElementById(a),d=(new Vex.Flow.Renderer(c,this.backend)).getContext();d.clearRect(0,0,c.width,c.height);b.setNoteStartX(this.note_spacer);b.setContext(d).draw(d,!1,!1)};
Games.Notation.NotationController.prototype.drawKeySignature=function(a,b,c){a=document.getElementById(a);var d=(new Vex.Flow.Renderer(a,this.backend)).getContext();this.clearKeySignature(b);d.clearRect(0,0,a.width,a.height);b.addKeySignature(c).setContext(d).draw(d,!1,!1)};Games.Notation.NotationController.prototype.clearKeySignature=function(a){var b;for(b=a.glyphs.length-1;0<b;b--)a.glyphs.pop(b)};
Games.Notation.NotationController.prototype.drawTimeSignature=function(a,b,c){a=document.getElementById(a);a=(new Vex.Flow.Renderer(a,this.backend)).getContext();b.addTimeSignature(c).setContext(a).draw(a,!1,!1)};Games.Notation.NotationController.prototype.clearTimeSignature=function(a){var b,c;for(b=a.glyphs.length-1;0<=b;b--)c=a.glyphs[b].code,"v0"===c&&a.glyphs.pop(b)};Games.Notation.NotationController.prototype.getNoteValue=function(){return notationModel.getNoteValue()};
Games.Notation.NotationController.prototype.setRangeIndex=function(a){notationModel.setRangeIndex(a)};Games.Notation.NotationController.prototype.getRandomClefIndex=function(a,b){return notationModel.randomClefIndex(a,b)};Games.Notation.NotationController.prototype.getRandomKeySignature=function(){return notationModel.randomKeySignature()};Games.Notation.NotationModel=function(){var a=cfg.MIN_RANGE_INDEX,b=cfg.TREBLE,c=0,d=0,e=-1,f=-1,g=-1,h=cfg.C,k=cfg.KEY_SIGS[h],l=cfg.SINGLE_C,m=!1,n=cfg.ACC_TYPE_C,p=!1;this.KS_MIN=cfg.CF;this.KS_MAX=cfg.CS;this.getRangeIndex=function(){return a};this.setRangeIndex=function(b){b<cfg.MIN_RANGE_INDEX&&(a=cfg.MIN_RANGE_INDEX);a=b>cfg.MAX_RANGE_INDEX?cfg.MAX_RANGE_INDEX:b};this.getClefIndex=function(){return b};this.setClefIndex=function(a){c=b;b=a};this.getPrevClefIndex=function(){return c};this.setPrevClefIndex=
function(a){c=a};this.getNoteIndex=function(){return d};this.setNoteIndex=function(a){d=0<=a?a:0;6<d&&(d=6)};this.getOctave=function(){return e};this.setOctave=function(a){e=a};this.getNoteValue=function(){return f};this.setNoteValue=function(a){f=Vex.Flow.keyProperties(a,cfg.CLEF_TYPES[b]).int_value%12};this.getKeySignatureLevel=function(){return g};this.setKeySignatureLevel=function(a){g=a};this.getKeySigIndex=function(){return h};this.setKeySigIndex=function(a){h=a};this.getKeySignature=function(){return k};
this.setKeySignature=function(a){k=cfg.KEY_SIGS[a]};this.updateKeySignature=function(a){h+=a;h=0>a?h>=cfg.CF?h:cfg.CF:h<=cfg.CS?h:cfg.CS;k=cfg.KEY_SIGS[h];this.convertNoteValue()};this.setAccidental=function(a){this.accidental=a;return this};this.getAccidental=function(){return this.accidental};this.getAccidentalRange=function(){return l};this.setAccidentalRange=function(a){l=a};this.getAddAccidental=function(){return m};this.setAddAccidental=function(a){m=a};this.getAccidentalType=function(){return n};
this.setAccidentalType=function(a){n=a};this.getAddKeySignature=function(){return p};this.setAddKeySignature=function(a){p=a};this.clefIndexArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];this.clefIndexProperties={0:!0,1:!1,2:!1,3:!1};this.keysig_acc_type={sharp:"#",flat:"b"}};Games.Notation.NotationModel.prototype.convertNoteIndex=function(){var a=this.getNoteIndex(),b=this.getClefIndex(),c=this.getPrevClefIndex(),d=[0,2,1,6];this.setNoteIndex(Math.abs((a-(d[c]-d[b]))%7))};
Games.Notation.NotationModel.prototype.convertNoteValue=function(){notationModel.getClefIndex();var a=this.getNoteIndex(),b=Vex.Flow.integerToNoteLetter(a),c=this.checkOctaveRange(),b=b+Flash.Notes.Keyboard.keySignatureAccidentals(this.getKeySignature(),a);this.setNoteValue(""+b+"/"+c)};
Games.Notation.NotationModel.prototype.checkOctaveRange=function(){var a=this.getOctave(),b=this.getClefIndex(),c=this.getRangeIndex(),d=this.getNoteIndex(),e=Flash.Notes.Keyboard.noteRangeProperties(b),b=e.base_octave[c],f=e.upper_octave[c],g=e.base_index[c],c=e.upper_index[c];a<b&&(a=b);a===b&&d<g&&(a=b+1);a>f&&(a=f);a===f&&d>c&&(a=f-1);return a};Games.Notation.NotationModel.prototype.randomClefIndex=function(a,b){return this.clefIndexArray[Math.round(100*Math.random())%a+b]};
Games.Notation.NotationModel.prototype.practiceClefIndex=function(){var a,b;for(a=0;4>a;a++)if(b=this.clefIndexProperties[a])return this.clefIndexArray[a];return null};
Games.Notation.NotationModel.prototype.randomAccidental=function(){var a=this.getAccidentalRange(),b=null,c=[null,"b","#","bb","##","n"],d=[null,"b","#","n"],e=[null,"bb","##"],f=c.length,g=d.length,h=e.length;this.getNoteIndex();this.getKeySignature();switch(a){case cfg.ACC_ALL:a=Math.round(1E3*Math.random())%(f-1);b=c[a];break;case cfg.ACC_ALL_NOT_C:a=Math.round(1E3*Math.random())%f;(b=c[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_SINGLE:a=Math.round(1E3*Math.random())%(g-1);b=d[a];break;
case cfg.ACC_SINGLE_NOT_C:a=Math.round(1E3*Math.random())%g;(b=d[a])&&(b=this.filterAccidental(b));break;case cfg.ACC_DOUBLE:a=Math.round(1E3*Math.random())%h,b=e[a]}return b};Games.Notation.NotationModel.prototype.filterAccidental=function(a){var b=this.getKeySignature(),c=this.getNoteIndex(),b=Flash.Notes.Keyboard.keySignatureAccidentals(b,c);return"##"===a||"bb"===a?a:"n"===a?""!=b?a:null:""==b?a:null};
Games.Notation.NotationModel.prototype.randomKeySignature=function(){var a;this.getKeySignatureLevel()===cfg.EASY_KEYS?(a=cfg.KS_EASY.length,a=Math.round(1E3*Math.random())%a,a=cfg.KS_EASY[a]):(a=cfg.KS_HARD.length,a=Math.round(1E3*Math.random())%a,a=cfg.KS_HARD[a]);return a};
Games.Notation.NotationModel.prototype.getImgUrl=function(a){switch(a){case cfg.TREBLE:return"images/treble.png";case cfg.BASS:return"images/bass.png";case cfg.ALTO:return"images/c_clef.png";case cfg.TENOR:return"images/c_clef.png";default:return"images/treble.png"}};Games.Notation.NotationModel.prototype.getClefOffset=function(a){switch(a){case cfg.TREBLE:return cfg.TREBLE_OFFSET;case cfg.BASS:return cfg.BASS_OFFSET;case cfg.ALTO:return cfg.ALTO_OFFSET;case cfg.TENOR:return cfg.TENOR_OFFSET;default:return cfg.TREBLE_OFFSET}};Box=function(a,b,c){0<arguments.length&&this.init(a,b,c)};Box.prototype.init=function(a,b,c){this.x=document.getElementById(a).getAttribute("left");this.y=document.getElementById(a).getAttribute("top");this.width=b;this.height=c;this.paper=Raphael(a,this.width,this.height);this.attributes={stroke_width:0,fill:"beige",stroke:"beige"};this.bg_attributes={stroke_width:0,fill:"white",stroke:"white"}};Box.prototype.ctx=function(){return this.paper};
Box.prototype.setStrokeColor=function(a){this.attributes.stroke=a;return this};Box.prototype.setStrokeWidth=function(a){this.attributes.stroke_width=a;return this};Box.prototype.setFill=function(a){this.attributes.fill=a;return this};Box.prototype.fillRect=function(a,b,c,d){0>d&&(b+=d,d=-d);this.rectangle=this.paper.rect(a,b,c,d).attr(this.attributes);return this};Box.prototype.getRect=function(){return this.rectangle};Button=function(a,b,c,d,e,f){0<arguments.length&&this.init(a,b,c,d,e)};Button.prototype.init=function(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.id=e;this.path=this.label=""};Button.prototype.imgString=function(a){return this.imgString=""+a+" "+this.x+" "+this.y+" "+this.w+" "+this.h};Button.prototype.clickHandler=function(){return this.id};Clef=function(a,b,c,d,e){this.src=e;this.x=a+.35*c;this.y=b;this.offset=this.w=this.h=0;switch(d){case 0:this.y=b-1.25*c;this.h=6.7*c;this.w=.4*this.h;this.offset=10;break;case 1:this.h=3.4*c;this.w=.69*this.h;this.offset=12;break;case 2:this.h=4*c;this.w=.75*this.h;this.offset=11;break;case 3:this.y=b-c,this.h=4*c,this.w=.75*this.h,this.offset=9}};Lives=function(a,b,c){0<arguments.length&&this.init(a,b,c)};Lives.prototype.init=function(a,b,c){this.attributes={stroke_width:0,fill:"#447",stroke:"#eee"};this.width=b;this.height=c;this.paper=Raphael(a,this.width,this.height)};Lives.prototype.ctx=function(){return this.paper};Lives.prototype.setStrokeColor=function(a){this.attributes.stroke=a;return this};Lives.prototype.setStrokeWidth=function(a){this.attributes.stroke_width=a;return this};
Lives.prototype.setFill=function(a){this.attributes.fill=a;return this};Lives.prototype.fillRect=function(a,b,c,d){0>d&&(b+=d,d=-d);this.rectangle=this.paper.rect(a,b,c,d).attr(this.attributes);return this};Lives.prototype.getRect=function(){return this.rectangle};Flash.Notes.Keyboard.NotationView=function(a,b,c){this.PROPS={numLines:5,space:14,ledgerLines:1,numPos:15};this.box=new Box(a,b,c);this.paper=this.box.ctx();this.RECT_X=42;this.RECT_Y=0;this.RECT_W=b-42;this.RECT_H=(6+2*this.PROPS.ledgerLines+this.PROPS.numLines+1)*this.PROPS.space;this.STAFF_X=this.RECT_X+10;this.STAFF_Y=this.RECT_Y+(4+this.PROPS.ledgerLines)*this.PROPS.space;this.STAFF_W=this.RECT_W-20;this.staff=new Staff(this.STAFF_X,this.STAFF_Y,this.STAFF_W,this.PROPS);this.valueOffset=this.clefType=
this.notePos=-1};Flash.Notes.Keyboard.NotationView.prototype.staffPath=function(){return this.staff.path()};Flash.Notes.Keyboard.NotationView.prototype.clef=function(a,b){return new Clef(this.STAFF_X,this.STAFF_Y,this.PROPS.space,a,b)};Flash.Notes.Keyboard.NotationView.prototype.note=function(a,b){var c=new Note(this.STAFF_X+this.STAFF_W/2,b.bottomPos(),a,this.PROPS.space,"images/whole.png");this.pos=a;return c};Flash.Notes.Keyboard.NotationView.prototype.keySignature=function(){};
Flash.Notes.Keyboard.NotationView.prototype.accidental=function(){};Flash.Notes.Keyboard.NotationView.prototype.ledgerLinePath=function(a,b){var c=0,d=Math.abs(a),e="";0<a&&(c=1);0>a&&(c=-1);switch(c){case 1:e+=b.ledgerPath(this.STAFF_Y+5*this.PROPS.space,d,c);break;case -1:e+=b.ledgerPath(this.STAFF_Y-this.PROPS.space,d,c)}return e};ScoreKeeper=function(){};ScoreKeeper.prototype.pointDisplay=function(a,b,c,d,e){};ScoreKeeper.prototype.percentDisplay=function(a,b,c,d,e){};ScoreKeeper.prototype.scoreDisplay=function(a,b,c,d,e){};ScoreKeeper.prototype.toggleDisplay=function(a,b,c,d){};Staff=function(a,b,c,d){this.x=a;this.y=b;this.w=c;this.props={numOfLines:5,space:18,ledgerLines:3,numOfPositions:23};this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;Merge(this.props,d)};Staff.prototype.path=function(){for(var a="",b=this.getNumOfLines(),c=this.x,d=this.x+this.w,e=0;e<b;e++)var f=this.y+e*this.getSpace(),a=a+("M "+c+" "+f+" L "+d+" "+f);return a};Staff.prototype.getProps=function(){return this.props};Staff.prototype.setNumOfLines=function(a){this.props.numOfLines=a;return this};
Staff.prototype.setSpace=function(a){this.props.space=a;return this};Staff.prototype.setLedgerLines=function(a){this.props.ledgerLines=a;return this};Staff.prototype.setNumOfPositions=function(){this.props.numOfPositions=2*(this.getNumOfLines+2*this.getLedgerLines())+1;return this};Staff.prototype.getNumOfLines=function(){return this.props.numOfLines};Staff.prototype.getSpace=function(){return this.props.space};Staff.prototype.getLedgerLines=function(){return this.props.ledgerLines};
Staff.prototype.getNumOfPositions=function(){return this.props.numOfPositions};Staff.prototype.bottomPos=function(){return this.y+(this.getNumOfLines()-1+this.getLedgerLines())*this.getSpace()};Staff.prototype.topPos=function(){return this.y-(this.getLedgerLines()+1)*this.getSpace()};Staff.prototype.ledgerLines=function(a){var b=2*this.getLedgerLines()-1,c=2*(this.getLedgerLines()+this.getNumOfLines())+1,d=0;a<=b&&(d=1+Math.floor((b-a)/2));a>=c&&(d=-1-Math.floor((a-c)/2));return d};
Staff.prototype.getPosY=function(a){return a>this.getNumOfPositions()-1?this.getTopPos():0>a?this.getBottomPos():this.getBottomPos()+a*(this.getSpace()/2)};StaffArea=function(a,b,c,d){this.RECT_X=150;this.RECT_Y=100;this.RECT_W=300;0<arguments.length&&this.init(a,b,c,d)};StaffArea.prototype.init=function(a,b,c,d){this.x=a;this.y=b;this.width=c;this.height=d;this.paper=Raphael(this.x,this.y,this.width,this.height);this.attributes={stroke_width:0,fill:"beige",stroke:"beige"};this.bg_attributes={stroke_width:0,fill:"white",stroke:"white"}};StaffArea.prototype.ctx=function(){return this.paper};
StaffArea.prototype.setStrokeColor=function(a){this.attributes.stroke=a;return this};StaffArea.prototype.setStrokeWidth=function(a){this.attributes.stroke_width=a;return this};StaffArea.prototype.setFill=function(a){this.attributes.fill=a;return this};StaffArea.prototype.fillRect=function(a,b,c,d){0>d&&(b+=d,d=-d);this.paper.rect(a,b,c,d).attr(this.attributes);return this};StaffArea.prototype.addStaff=function(a){return this.paper.path(a.path())};Timer=function(){};Timer.prototype.timeDisplay=function(a,b,c,d,e){};Flash.Notes.Keyboard.GameController=function(){var a=!1;this.getMaxLevel=function(){return a};this.setMaxLevel=function(b){a=b};this.canvas_id="staff";this.init()};
Flash.Notes.Keyboard.GameController.prototype.init=function(){statusModel.start(!1);statusModel.setTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setLevel(1);statusModel.setPoints(0);statusModel.setAttempts(0);statusModel.setScore(0);statusModel.setLives(cfg.MAX_LIVES);statusModel.setOverlayVisible(!1);statusView.displayKeyOverlay(!1);statusView.displayTime("#status_timer",0);this.stave=notationController.drawStaff(this.canvas_id,10,20,330,cfg.LARGE);notationController.hideNote(this.canvas_id,
this.stave);notationController.drawClef("staff",this.stave,"treble");notationModel.setKeySigIndex(cfg.KS_C_INDEX);notationModel.setClefIndex(cfg.TREBLE);notationModel.setAddAccidental(!1);notationModel.setAccidentalRange(cfg.ACC_NONE);notationModel.setAccidental(cfg.NONE);notationModel.setKeySignature(cfg.C);notationController.drawKeySignature(this.canvas_id,this.stave,"C",cfg.TREBLE);notationController.setRangeIndex(cfg.MIN_RANGE_INDEX);$("#start_button").hide();$("#stop_button").hide();this.initClefs(cfg.TREBLE);
this.initAccidentals();this.displayScore();this.startx=120;return this};Flash.Notes.Keyboard.GameController.prototype.displayPractice=function(){this.init();this.setMode(cfg.PRACTICE_MODE);$("#menu_frame").hide();$("#status_level_label").html("");$("#status_level").html("");$("#game_frame").show();$("#menu_buttons").show();$("#game_status_box").hide();$("#stop_button").hide();$("#start_button").show();statusView.initHitDisplay("hit_light")};
Flash.Notes.Keyboard.GameController.prototype.displayGame=function(){this.init();this.setMode(cfg.GAME_MODE);statusView.initLivesDisplay("game_lives",cfg.MAX_LIVES);statusView.initHitDisplay("hit_light");$("#status_level_label").html("Level:");$("#status_level").html("1");this.displaySessionAlert(!0,!1,!1)};Flash.Notes.Keyboard.GameController.prototype.setMode=function(a){statusModel.setMode(a)};
Flash.Notes.Keyboard.GameController.prototype.initClefs=function(a){var b;for(b=0;4>b;b++)statusModel.active_clefs[b]=!1,statusModel.clefButtons[b].removeClass("on"),statusModel.clefButtons[b].addClass("off");statusModel.active_clefs[a]=!0;statusModel.clefButtons[a].removeClass("off");statusModel.clefButtons[a].addClass("on")};
Flash.Notes.Keyboard.GameController.prototype.initAccidentals=function(){statusModel.accidental_on=!1;$("#acc_single_sel_button").removeClass("on");$("#acc_single_sel_button").addClass("off");$("#acc_double_sel_button").removeClass("on");$("#acc_double_sel_button").addClass("off");cfg.ACCIDENTAL_ON.single_acc=!1;cfg.ACCIDENTAL_ON.double_acc=!1};
Flash.Notes.Keyboard.GameController.prototype.startGame=function(a){var b=statusModel.getStart(),c=statusModel.getMode();notationModel.getClefIndex();statusModel.keyId="c";if(b)this.stopGame();else{statusModel.start(!0);document.getElementById("c").focus();switch(c){case cfg.GAME_MODE:this.startTimer(a,statusModel.getTimeInterval(),c);break;case cfg.PRACTICE_MODE:this.startTimer(a,0,c)}notationController.drawKeySignature(this.canvas_id,this.stave,notationModel.getKeySignature(),notationModel.getClefIndex());
a=this.getNoteName();notationController.drawNote(this.canvas_id,this.stave,a,"w",Vex.Flow.TIME4_4,this.startx,notationModel.getAccidental())}};
Flash.Notes.Keyboard.GameController.prototype.getNoteName=function(){var a=notationModel.getRangeIndex(),b=notationModel.getClefIndex(),c,d=Flash.Notes.Keyboard.noteRangeProperties(b),e=d.upper_octave[a]-d.base_octave[a]+1,f=Math.round(10*Math.random())%e,g=d.base_octave[a]+f;notationModel.setOctave(g);0===f?(e=d.base_index[a],a=6-e):f===e-1?(e=0,a=d.upper_index[a]):(e=0,a=6);a=e+(0<a?Math.round(1E4*Math.random())%a:0);notationModel.setNoteIndex(a);a=Vex.Flow.integerToNoteLetter(a);notationModel.getAddAccidental()&&
(c=notationModel.randomAccidental(),notationModel.setAccidental(c),c&&(a+=c,notationController.drawKeySignature(this.canvas_id,this.stave,notationModel.getKeySignature(),b)));notationModel.getAddKeySignature()&&!c&&(a+=Flash.Notes.Keyboard.keySignatureAccidentals(notationModel.getKeySignature(),notationModel.getNoteIndex()),notationController.drawKeySignature(this.canvas_id,this.stave,notationModel.getKeySignature(),b));a=""+a+"/"+g+"";notationModel.setNoteValue(a);return a};
Flash.Notes.Keyboard.GameController.prototype.startTimer=function(a,b,c){var d,e=this;0>b?(clearTimeout(this.getT),statusModel.setTimeout(!0),this.stopGame()):d=setTimeout(function(){e.updateTimer(a,b,c,d)},1E3);statusView.displayTime(a,b);return this};
Flash.Notes.Keyboard.GameController.prototype.updateTimer=function(a,b,c,d){statusModel.getStart()&&c===cfg.GAME_MODE?(--b,statusModel.setTime(b),statusModel.setTimeInterval(b),this.startTimer(a,b,c,d)):statusModel.getStart()&&c===cfg.PRACTICE_MODE&&(b+=1,statusModel.setTime(b),this.startTimer(a,b,c,d))};
Flash.Notes.Keyboard.GameController.prototype.continueGame=function(a,b){var c,d=statusModel.getStart(),e=statusModel.getLevel(),f=statusModel.getMode()===cfg.GAME_MODE?!0:!1;statusModel.keyCode=parseInt(a)%12;statusModel.value=notationController.getNoteValue();(c=statusModel.keyCode===statusModel.value?!0:!1)?statusView.updateHitDisplay(!0):statusView.updateHitDisplay(!1);f&&!c&&(statusModel.decLives(),statusModel.getLives(),statusView.updateLivesDisplay());d&&c&&(this.getMaxLevel()?(c=notationController.getRandomClefIndex(4,
0),notationModel.setClefIndex(clefIndex),c=cfg.CLEF_TYPES[c],notationController.drawClef(this.canvas_id,this.stave,c)):(5<=e&&8>=e&&(c=notationController.getRandomClefIndex(2,0),notationModel.setClefIndex(c),c=cfg.CLEF_TYPES[c],notationController.drawClef(this.canvas_id,this.stave,c)),13<=e&&16>=e&&(c=notationController.getRandomClefIndex(2,2),notationModel.setClefIndex(c),c=cfg.CLEF_TYPES[c],notationController.drawClef(this.canvas_id,this.stave,c))),f||(c=statusModel.getRandomClefIndex(),notationModel.setClefIndex(c),
c=cfg.CLEF_TYPES[c],this.setPracticeRange(),notationController.drawClef(this.canvas_id,this.stave,c)),notationModel.getClefIndex(),notationController.hideNote(this.canvas_id,this.stave),note=notationController.drawNote(this.canvas_id,this.stave,this.getNoteName(),"w",Vex.Flow.TIME4_4,this.startx,notationModel.getAccidental()),statusModel.addPoint(),statusModel.calculateScore());d&&(statusModel.addAttempt(),this.displayScore(),document.getElementById(Flash.Notes.Keyboard.keyIdToElementId(b)).focus())};
Flash.Notes.Keyboard.GameController.prototype.stopGame=function(){var a,b;statusModel.start(!1);notationController.hideNote(this.canvas_id,this.stave);notationController.drawKeySignature(this.canvas_id,this.stave,notationModel.getKeySignature(),notationModel.getClefIndex());document.getElementById(statusModel.keyId).blur();statusModel.getMode()===cfg.GAME_MODE?(a=statusModel.isLevelAdvance(),b=0<statusModel.getLives()?!1:!0,a&&(statusModel.advanceLevel(),statusModel.addBonus()),this.displaySessionAlert(!1,
b,a)):(notationController.setRangeIndex(cfg.MIN_RANGE),$("#stop_button").hide(),$("#start_button").show(),this.displaySummary());return this};Flash.Notes.Keyboard.GameController.prototype.resetGame=function(){statusModel.setTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setPoints(0);statusModel.setAttempts(0);this.displayScore()};Flash.Notes.Keyboard.GameController.prototype.getStart=function(){return statusModel.getStart()};
Flash.Notes.Keyboard.GameController.prototype.toggleClef=function(a){if(!statusModel.getStart()){var b=statusModel.toggleClefButton(a);notationModel.getClefOffset(a);notationModel.getRangeIndex();switch(b){case cfg.TOGGLE_ON:statusModel.clefButtons[a].removeClass("off");statusModel.clefButtons[a].addClass("on");notationModel.clefIndexProperties[a]=!0;notationController.drawClef(this.canvas_id,this.stave,cfg.CLEF_TYPES[a]);notationModel.setClefIndex(a);notationController.drawKeySignature(this.canvas_id,
this.stave,notationModel.getKeySignature(),notationModel.getClefIndex());break;case cfg.TOGGLE_OFF:statusModel.clefButtons[a].removeClass("on"),statusModel.clefButtons[a].addClass("off"),notationModel.clefIndexProperties[a]=!1,a=notationModel.practiceClefIndex(),notationController.drawClef(this.canvas_id,this.stave,cfg.CLEF_TYPES[a]),notationModel.setClefIndex(a),notationController.drawKeySignature(this.canvas_id,this.stave,notationModel.getKeySignature(),notationModel.getClefIndex())}}};
Flash.Notes.Keyboard.GameController.prototype.toggleAccidental=function(a){if(!statusModel.getStart()){a=statusModel.toggleAccidental(a);var b=notationModel.getKeySignature();notationModel.getAccidentalRange();addAccidental=cfg.ACCIDENTAL_ON.single_acc||cfg.ACCIDENTAL_ON.double_acc?!0:!1;notationModel.setAddAccidental(addAccidental);switch(a){case cfg.ACC_SINGLE:$("#acc_single_sel_button").removeClass("off");$("#acc_single_sel_button").addClass("on");$("#acc_double_sel_button").removeClass("on");
$("#acc_double_sel_button").addClass("off");b===cfg.C?notationModel.setAccidentalRange(cfg.ACC_SINGLE):notationModel.setAccidentalRange(cfg.ACC_SINGLE_NOT_C);break;case cfg.ACC_DOUBLE:$("#acc_single_sel_button").removeClass("on");$("#acc_single_sel_button").addClass("off");$("#acc_double_sel_button").removeClass("off");$("#acc_double_sel_button").addClass("on");notationModel.setAccidentalRange(cfg.ACC_DOUBLE);break;case cfg.ACC_ALL:$("#acc_single_sel_button").removeClass("off");$("#acc_single_sel_button").addClass("on");
$("#acc_double_sel_button").removeClass("off");$("#acc_double_sel_button").addClass("on");b===cfg.C?notationModel.setAccidentalRange(cfg.ACC_ALL):notationModel.setAccidentalRange(cfg.ACC_ALL_NOT_C);break;case cfg.ACC_NONE:$("#acc_single_sel_button").removeClass("on"),$("#acc_single_sel_button").addClass("off"),$("#acc_double_sel_button").removeClass("on"),$("#acc_double_sel_button").addClass("off"),notationModel.setAccidentalRange(cfg.ACC_NONE)}}};
Flash.Notes.Keyboard.GameController.prototype.toggleKeyOverlay=function(){statusModel.setOverlayVisible(!statusModel.getOverlayVisible());statusView.displayKeyOverlay(statusModel.getOverlayVisible())};
Flash.Notes.Keyboard.GameController.prototype.updateKeySignature=function(a){statusModel.getStart()||(notationModel.updateKeySignature(a),a=notationModel.getKeySigIndex(),notationController.drawKeySignature(this.canvas_id,this.stave,cfg.KEY_SIGS[a],notationModel.getClefIndex()),a!=cfg.C?(notationModel.setAddKeySignature(!0),cfg.ACCIDENTAL_ON.single_acc&&!cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_SINGLE_NOT_C),cfg.ACCIDENTAL_ON.single_acc&&cfg.ACCIDENTAL_ON.double_acc&&
notationModel.setAccidentalRange(cfg.ACC_ALL_NOT_C)):(notationModel.setAddKeySignature(!1),cfg.ACCIDENTAL_ON.single_acc&&!cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_SINGLE),cfg.ACCIDENTAL_ON.single_acc&&cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_ALL)),!cfg.ACCIDENTAL_ON.single_acc&&cfg.ACCIDENTAL_ON.double_acc&&notationModel.setAccidentalRange(cfg.ACC_DOUBLE),cfg.ACCIDENTAL_ON.single_acc||cfg.ACCIDENTAL_ON.double_acc||notationModel.setAccidentalRange(cfg.ACC_NONE),
notationModel.convertNoteValue())};Flash.Notes.Keyboard.GameController.prototype.setPracticeRange=function(){var a=statusModel.getPercent(),b=statusModel.getAttempts(),c=notationModel.getRangeIndex();a>=cfg.P_HIGH_PCT&&0===b%cfg.PRACTICE_ATT&&c<cfg.MAX_RANGE&&(notationController.setRangeIndex(c+1),notationModel.setRangeIndex(c+1));a<cfg.P_LOW_PCT&&c>cfg.MIN_RANGE&&(notationController.setRangeIndex(c-1),notationModel.setRangeIndex(c-1))};
Flash.Notes.Keyboard.GameController.prototype.updateLevel=function(){var a=statusModel.getLevel(),b=0===a%2?a/2-1:Math.floor(a/2),c,d;statusModel.setGameClefTypes();c=statusModel.getRandomClefIndex();d=cfg.CLEF_TYPES[c];b%=cfg.MAX_RANGE+1;if(a===cfg.MAX_LEVEL)this.setMaxLevel(!0),notationModel.setKeySignature(notationModel.randomKeySignature()),notationController.drawClef(this.canvas_id,this.stave,notationController.getRandomClefIndex(4,0)),notationModel.setClefIndex(c),notationController.setRangeIndex(cfg.MAX_RANGE),
notationModel.setRangeIndex(cfg.MAX_RANGE);else{switch(c){case cfg.RANDOM_TB:c=notationController.getRandomClefIndex(2,0);d=cfg.CLEF_TYPES[c];notationController.drawClef(this.canvas_id,this.stave,d);notationModel.setClefIndex(c);break;case cfg.RANDOM_AT:c=notationController.getRandomClefIndex(2,2);d=cfg.CLEF_TYPES[c];notationController.drawClef(this.canvas_id,this.stave,d);notationModel.setClefIndex(c);break;default:notationController.drawClef(this.canvas_id,this.stave,d),notationModel.setClefIndex(c)}notationController.setRangeIndex(b);
notationModel.setRangeIndex(b)}statusModel.isAccidentalLevel()?notationModel.setAddAccidental(!0):notationModel.setAddAccidental(!1);statusModel.isKeySignatureLevel()?(notationModel.setAddKeySignature(!0),notationModel.setKeySignatureLevel(statusModel.getKeySignatureLevel()),notationModel.setKeySignature(notationModel.randomKeySignature())):(notationModel.setAddKeySignature(!1),notationModel.setKeySignature(cfg.C));statusModel.getTimeout()&&this.resetGame();this.displayScore();this.displaySessionAlert(!0,
!1,!1)};Flash.Notes.Keyboard.GameController.prototype.displayScore=function(){statusView.displayPoints("#status_points",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#status_percent",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#status_score",statusModel.getScore());statusModel.getMode()===cfg.GAME_MODE&&statusView.displayLevel("#status_level",statusModel.getLevel());statusView.displayHiScore("#hi_score",statusModel.getHiScore())};
Flash.Notes.Keyboard.GameController.prototype.displaySummary=function(){var a;$("#game_frame").hide();statusView.displayPoints("#point_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#percent_summary",statusModel.getPoints(),statusModel.getAttempts());statusModel.getMode()===cfg.PRACTICE_MODE&&($("#score_summary_row").hide(),$("#level_summary_row").hide(),$("#lives_summary_row").hide(),$("#next_level_row").hide(),$("#time_summary_row").show(),a=statusModel.getTime()?
statusModel.getTime():0,$("#time_summary").html(""+a+" sec"));statusModel.getMode()===cfg.GAME_MODE&&(statusView.displayScore("#score_summary",statusModel.getScore()),$("#time_summary_row").hide(),$("#score_summary_row").show(),$("#level_summary_row").show(),$("#lives_summary_row").show(),$("#next_level_row").show(),$("#level_summary").html(""+statusModel.getLevel()),$("#lives_summary").html(""+statusModel.getLives()));$("#summary_frame").show()};
Flash.Notes.Keyboard.GameController.prototype.removeLivesDisplay=function(){statusModel.getMode()===cfg.GAME_MODE&&statusView.removeLivesDisplay()};
Flash.Notes.Keyboard.GameController.prototype.displaySessionAlert=function(a,b,c){$("#menu_frame").hide();$("#instructions_frame").hide();$("#summary_frame").hide();$("#game_frame").hide();$("#menu_buttons").hide();$("#session_frame").show();$("#game_status_box").show();a&&!b?($("#session_start_header").html("Level "+statusModel.getLevel()),$("#session_end").hide(),$("#game_end").hide(),$("#session_start").show(),$("#session_start_button").focus()):b?($("#session_start").hide(),$("#session_end").hide(),
$("#game_end").show(),$("#scores_button").focus()):($("#session_start").hide(),$("#game_end").hide(),lives=statusModel.getLives(),lives_str=1<lives?" lives":" life",$("#lives").html(""+statusModel.getLives()+lives_str+" left"),c?$("#bonus").html("BONUS PTS<br/>"+statusModel.getBonus()):$("#bonus").html("BONUS PTS<br/>0"),$("#session_end").show(),$("#session_end_button").focus())};
Flash.Notes.Keyboard.GameController.prototype.processFinalScore=function(){var a,b;a=statusModel.getScore();var c,d;statusModel.setDate();b=statusModel.getDateTime();c=statusModel.getDateString();d=statusModel.getTimeString();b="score="+a+"&time="+b+"&date_string="+c+"&time_string="+d;Modernizr.localstorage?(c=statusModel.getHiScore(),statusModel.setHiScore(c>a?c:a)):statusModel.setHiScore(a);$("#score_text").html("Please wait . . . retrieving scores");ajaxUtilities.createXHR();a=ajaxUtilities.getXHR();
ajaxUtilities.open("POST","php/get_scores.php");a.onreadystatechange=ajaxUtilities.onChange;ajaxUtilities.send("POST",b)};
Flash.Notes.Keyboard.GameController.prototype.displayFinalScore=function(a){var b,c,d,e="",f="",g="",h="your score: "+statusModel.getScore(),k=statusModel.top_scores.length;if(a)for(a=0;a<k;a++)b=parseInt(statusModel.top_scores[a]),c=statusModel.top_date_strings[a],d=parseInt(statusModel.top_times[a]),b===statusModel.getScore()&&d===statusModel.getDateTime()?(e+='<span class="your_scores">'+(a+1)+".</span><br />",f+='<span class="your_scores">'+b+"*</span><br />",g+='<span class="your_scores">'+c+
"</span><br />",h="* your score"):(e+=a+1+".<br />",f+=b+"<br />",g+=c+"<br />");else for(a=0;10>a;a++)e+=a+1+".<br />",f+="unavailable<br />",g+="unavailable<br />";$("#score_display_frame").show();$("#main_menu_button").focus();$("#top_rank").html(e);$("#top_scores").html(f);$("#top_dates").html(g);$("#top_score_footer").html(h)};Flash.Notes.Keyboard.StatusModel=function(){var a,b,c,d,e=0,f=0,g=0,h=0,k=0,l=5,m=!1,n=cfg.TIMEOUT,p=!1,r=!1,t,q;q=Modernizr.localstorage?(t=parseInt(localStorage.getItem("hiscore_keys")))?t:0:0;this.getTime=function(){return a};this.setTime=function(b){a=b};this.getMode=function(){return b};this.setMode=function(a){b=a};this.setDate=function(){c=new Date;d=c.getTime()};this.getDateTime=function(){return d};this.getDateString=function(){var a=""+(c.getMonth()+1),b=10>c.getDate()?"0"+c.getDate():c.getDate();
return a+"-"+b+"-"+c.getFullYear()};this.getTimeString=function(){var a=""+c.getHours(),b=10>c.getMinutes()?"0"+c.getMinutes():c.getMinutes(),d=10>c.getSeconds()?"0"+c.getSeconds():c.getSeconds();return a+":"+b+":"+d};this.addPoint=function(){e+=1};this.setPoints=function(a){e=a};this.getPoints=function(){return e};this.addAttempt=function(){f+=1};this.setAttempts=function(a){f=a};this.getAttempts=function(){return f};this.getPercent=function(){return Math.floor(e/f*100)};this.calculateScore=function(){g+=
e*h};this.addBonus=function(){k=cfg.BONUS*h;g+=k};this.getBonus=function(){return k};this.setScore=function(a){g=a};this.getScore=function(){return g};this.getHiScore=function(){return q};this.setHiScore=function(a){q=a;Modernizr.localstorage&&localStorage.setItem("hiscore_keys",q)};this.setLevel=function(a){h=a;h>cfg.BONUS_LEVEL&&(cfg.BONUS+=cfg.BONUS_INC)};this.getLevel=function(){return h};this.advanceLevel=function(){this.setLevel(h<cfg.MAX_LEVEL?h+=1:cfg.MAX_LEVEL);return this};this.decLives=
function(){--l;0>l&&(l=0)};this.setLives=function(a){l=a};this.getLives=function(){return l};this.start=function(a){m=a};this.getStart=function(){return m};this.setTimeInterval=function(a){n=a};this.getTimeInterval=function(){return n};this.setTimeout=function(a){p=a};this.getTimeout=function(){return p};this.getOverlayVisible=function(){return r};this.setOverlayVisible=function(a){r=a};this.top_scores=[];this.top_times=[];this.top_date_strings=[];this.top_time_strings=[];this.active_clefs=[!0,!1,
!1,!1];this.clefIndexArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];this.clefButtons=[$("#treble_button"),$("#bass_button"),$("#alto_button"),$("#tenor_button")]};Flash.Notes.Keyboard.StatusModel.prototype.isAccidentalLevel=function(){var a,b=cfg.ACC_LEVELS,c=b.length;for(a=0;a<c;a++)if(this.getLevel()===b[a])return!0;return!1};
Flash.Notes.Keyboard.StatusModel.prototype.isKeySignatureLevel=function(){return this.getLevel()>=cfg.KS_TIER_1[0]&&this.getLevel()<=cfg.KS_TIER_1[1]||this.getLevel()>=cfg.KS_TIER_2[0]&&this.getLevel()<=cfg.KS_TIER_2[1]?!0:!1};Flash.Notes.Keyboard.StatusModel.prototype.getKeySignatureLevel=function(){var a,b=cfg.KS_EASY_LEVELS,c=cfg.KS_HARD_LEVELS,d=b.length,e=c.length;for(a=0;a<d;a++)if(this.getLevel()===b[a])return cfg.EASY_KEYS;for(a=0;a<e;a++)if(this.getLevel()===c[a])return cfg.HARD_KEYS;return null};
Flash.Notes.Keyboard.StatusModel.prototype.isLevelAdvance=function(){return this.getPercent()>=cfg.MIN_PERCENT&&this.getTimeout()&&this.getAttempts()>=cfg.MIN_ATTEMPTS?!0:!1};Flash.Notes.Keyboard.StatusModel.prototype.setGameClefTypes=function(){var a,b=this.getLevel();b<=cfg.TIER_1&&(a=0===b%2,a=[!a,a,!1,!1]);b>cfg.TIER_1&&b<=cfg.TIER_2&&(a=[!0,!0,!1,!1]);b>cfg.TIER_2&&b<=cfg.TIER_3&&(a=0===b%2,a=[!1,!1,!a,a]);b>cfg.TIER_3&&b<=cfg.TIER_4&&(a=[!1,!1,!0,!0]);b>cfg.TIER_4&&(a=[!0,!0,!0,!0]);this.set_clef(a)};
Flash.Notes.Keyboard.StatusModel.prototype.set_clef=function(a){var b;for(b=0;4>b;b++)this.active_clefs[b]=a[b]};Flash.Notes.Keyboard.StatusModel.prototype.getRandomClefIndex=function(){var a,b=[],c=0;for(a=0;4>a;a++)!0===this.active_clefs[a]&&(b[c]=a,c+=1);1===b.length?a=b[0]:(a=Math.round(100*Math.random())%b.length,a=b[a]);return this.clefIndexArray[a]};
Flash.Notes.Keyboard.StatusModel.prototype.toggleClefButton=function(a){var b,c=0;if(this.active_clefs[a]){for(b=0;4>b;b++)c+=!0===this.active_clefs[b]?1:0;if(1===c)return cfg.TOGGLE_NONE}this.active_clefs[a]=!this.active_clefs[a];return this.active_clefs[a]?cfg.TOGGLE_ON:cfg.TOGGLE_OFF};
Flash.Notes.Keyboard.StatusModel.prototype.toggleAccidental=function(a){var b=cfg.ACCIDENTAL_ON,c;b[a]=!b[a];a=cfg.ACCIDENTAL_ON.single_acc;b=cfg.ACCIDENTAL_ON.double_acc;a&&!b&&(c=cfg.ACC_SINGLE);!a&&b&&(c=cfg.ACC_DOUBLE);a&&b&&(c=cfg.ACC_ALL);a||b||(c=cfg.ACC_NONE);return c};
Flash.Notes.Keyboard.StatusModel.prototype.getKeyIndex=function(a){switch(a){case cfg.KEY_C:return 0;case cfg.KEY_CS:return 1;case cfg.KEY_D:return 2;case cfg.KEY_DS:return 3;case cfg.KEY_E:return 4;case cfg.KEY_F:return 5;case cfg.KEY_FS:return 6;case cfg.KEY_G:return 7;case cfg.KEY_GS:return 8;case cfg.KEY_A:return 9;case cfg.KEY_AS:return 10;case cfg.KEY_B:return 11;case cfg.KEY_C2:return 12;default:return-1}};Flash.Notes.Keyboard.StatusView=function(){var a,b,c,d,e,f,g,h=[],k,l;this.initLivesDisplay=function(c,d){b=Raphael(c,60,20);for(a=0;a<d;a++)h[a]=b.circle(10*(a+1),5,4.5).attr({fill:"green",stroke:"#000"})};this.updateLivesDisplay=function(){k=h.length;0<k&&(h[k-1].remove(),h.pop())};this.removeLivesDisplay=function(){b.remove()};this.drawStatusBar=function(a,b,e,f){c=Raphael(a,b,e,f);d=c.rect(0,0,e,f);d.attr({stroke:"red",fill:"#202000"})};this.initHitDisplay=function(a){e=Raphael(a,0,0);f=e.path("M 5 18 L 17 30 L 33 2 L 17 23 Z").attr({stroke:"#447",
"stroke-width":1});g=e.path("M 5 5 L 35 35 M 35 5 L 5 35").attr({stroke:"#447","stroke-width":5});f.hide();g.hide()};this.removeHitDisplay=function(){e.remove();$(".hit_box").hide()};this.updateHitDisplay=function(a){a?(f.attr({stroke:"#0c2",fill:"#0c2"}),g.hide(),f.show()):(g.attr({stroke:"#f00"}),f.hide(),g.show());this.startHitTimer();$(".hit_box").show()};this.startHitTimer=function(){var a=this;l=setTimeout(function(){a.stopHitTimer()},600)};this.stopHitTimer=function(){f.hide();g.hide();$(".hit_box").hide();
clearTimeout(l)}};Flash.Notes.Keyboard.StatusView.prototype.displayTime=function(a,b){var c="00:",d=0<=b?""+b:""+(b+1);10>b&&(c="00:0");$(a).html(c+d)};Flash.Notes.Keyboard.StatusView.prototype.displayLevel=function(a,b){var c=""+b;$(a).html(c)};Flash.Notes.Keyboard.StatusView.prototype.displayPoints=function(a,b,c){b=""+b+"/"+c;$(a).html(b)};Flash.Notes.Keyboard.StatusView.prototype.displayPercent=function(a,b,c){b=""+(0<c?Math.round(b/c*100):0)+"%";$(a).html(b)};
Flash.Notes.Keyboard.StatusView.prototype.displayScore=function(a,b){var c=""+b;$(a).html(c)};Flash.Notes.Keyboard.StatusView.prototype.displayHiScore=function(a,b){var c=""+b;$(a).html(c)};
Flash.Notes.Keyboard.StatusView.prototype.displayKeyOverlay=function(a){var b=document.getElementById("black_keys"),c=document.getElementById("white_keys").getElementsByTagName("button"),b=b.getElementsByTagName("button"),d="c_ d_ e_ f_ g_ a_ b_ c2_".split(" "),e=["cs_","ds_","fs_","gs_","as_"],f,g;if(a){for(a=0;a<c.length;a++)f=d[a]+"overlay",g="#white_keys button:nth-child("+(a+1)+")",$(g).addClass(f);for(a=0;a<b.length;a++)f=e[a]+"overlay",g="#black_keys button:nth-child("+(a+1)+")",$(g).addClass(f)}else{for(a=
0;a<c.length;a++)f=d[a]+"overlay",g="#white_keys button:nth-child("+(a+1)+")",$(g).removeClass(f);for(a=0;a<b.length;a++)f=e[a]+"overlay",g="#black_keys button:nth-child("+(a+1)+")",$(g).removeClass(f)}};
